# Get-ChildItem "E:\mylaptop\CDesktop\offline\augustin mojarad ECUE 31 - Administration système\TP3 POWERSHELL\scripts\autres\2Découverte"
# directory=Get-ChildItem ".\"
# $directory.Where-objec

Get-ChildItem ".\" | Where-Object -Property Length -GT 100


#2 partie découverte 

#output 


# Mode                 LastWriteTime         Length Name                                                                                                                               
# ----                 -------------         ------ ----                                                                                                                               
# -a----        20/03/2021     14:57            180 script_2.PS1                                                                                                                       
# -a----        20/03/2021     15:04            259 script_3.PS1                                                                                                                       
